package codegen

import . "github.com/anz-bank/sysl/sysl2/codegen/golang" //nolint:golint,stylecheck

// Prelude creates a comment group indicating a generated file that shouldn't be edited.
func Prelude() *CommentGroup {
	return Comments(
		Commentf("//////////////////////////////////////////"),
		Commentf("//                                      //"),
		Commentf("//  AUTOGENERATED CODE -- DO NOT EDIT!  //"),
		Commentf("//                                      //"),
		Commentf("//////////////////////////////////////////"),
	)
}
